# Generated by Django 5.2.4 on 2025-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='right_answer',
            field=models.CharField(max_length=100),
        ),
    ]
